import { Theme } from '@themes/Theme'
import { colors } from '@themes/Colors'

export const lightTheme: Theme = {
  primaryColor: 'rgb(0, 122, 255)',
  backgroundColor: 'rgb(242, 242, 242)',
  separatorColor: colors.black,
  iconColor: colors.black,
  cardColor: 'lightgrey',
  listItemColor: 'lightgrey',
  selectedListItemColor: 'grey',
  h1Family: 'Poppins_400Regular',
  h1Size: 50,
  h1Color: colors.black,
  h2Family: 'Poppins_400Regular',
  h2Size: 35,
  h2Color: colors.black,
  h3Family: 'Poppins_400Regular',
  h3Size: 30,
  h3Color: colors.black,
  h4Family: 'Poppins_400Regular',
  h4Size: 25,
  h4Color: colors.black,
  h5Family: 'Poppins_400Regular',
  h5Size: 20,
  h5Color: colors.black,
  h6Family: 'Poppins_400Regular',
  h6Size: 15,
  h6Color: colors.black,
  textFamily: 'Poppins_400Regular',
  textSize: 10,
  textColor: colors.black,
  placeholderColor: colors.matteBlack,
}
